//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odluka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AHPEntities : DbContext
    {
        public AHPEntities()
            : base("name=AHPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AktivacijskiKod> AktivacijskiKods { get; set; }
        public virtual DbSet<Alternativa> Alternativas { get; set; }
        public virtual DbSet<Dnevnik> Dnevniks { get; set; }
        public virtual DbSet<FazaProjekta> FazaProjektas { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Projekt> Projekts { get; set; }
        public virtual DbSet<TipKorisnika> TipKorisnikas { get; set; }
        public virtual DbSet<TipZapisa> TipZapisas { get; set; }
        public virtual DbSet<Kriterij> Kriterijs { get; set; }
        public virtual DbSet<UsporedbaKriterija> UsporedbaKriterijas { get; set; }
    }
}
