//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odluka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alternativa
    {
        public int id { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public Nullable<int> projekt { get; set; }
        public Nullable<double> vrijednost { get; set; }
    
        public virtual Projekt Projekt1 { get; set; }
    }
}
