//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odluka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dnevnik
    {
        public int id { get; set; }
        public Nullable<int> tipZapisa { get; set; }
        public Nullable<System.DateTime> vrijeme { get; set; }
        public string dodatneInformacije { get; set; }
        public string stranica { get; set; }
        public Nullable<int> korisnik { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Korisnik Korisnik1 { get; set; }
        public virtual TipZapisa TipZapisa1 { get; set; }
    }
}
