//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odluka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsporedbaKriterija
    {
        public int kriterij1 { get; set; }
        public int kriterij2 { get; set; }
        public Nullable<double> vrijednost { get; set; }
    
        public virtual Kriterij Kriterij { get; set; }
        public virtual Kriterij Kriterij3 { get; set; }
    }
}
